# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration

#BIG FAT WARNING:
# Due the imlpementation of at_exit in Sensu::Handler sensu checks are 
# totally UNTESTABLE, because Sensu::Hander sets at_exit to read from STDIN 
# and it hangs and waits for some input."

def at_exit &block
  "WARNING: Monkey patching Kernel#at_exit see 'spec/spec_helper.rb'"
end

def exit code
  "WARNING: mocking exit with code #{code}"
  code
end

require 'spork'


Spork.prefork do
  require 'rspec'

  RSpec.configure do |config|
    config.treat_symbols_as_metadata_keys_with_true_values = true
    config.run_all_when_everything_filtered = true
    config.filter_run :focus
    #config.order = 'random'
    config.formatter = :documentation
    config.color_enabled = true
  end
end

Spork.each_run do
  require 'webmock/rspec'
  
  #require helpers
  require  File.join(File.dirname(__FILE__), 'virtualmaster_helper.rb')
  
  # include test config
  config_files = [
    File.join(File.dirname(__FILE__), '..', 'virtualmaster.json'),
    File.join(File.dirname(__FILE__), 'config', 'config.json')
  ]
  ENV['SENSU_CONFIG_FILES'] = config_files.join(":")

  load File.join(File.dirname(__FILE__), '../virtualmaster.rb')
end
